FROM apache/fluss-quickstart-flink:1.20-0.8.0-incubating

RUN wget -O /opt/flink/lib/fluss-lake-lance-0.8.0-incubating.jar https://repo1.maven.org/maven2/org/apache/fluss/fluss-lake-lance/0.8.0-incubating/fluss-lake-lance-0.8.0-incubating.jar \
    && wget -O /opt/flink/lib/fluss-fs-s3-0.8.0-incubating.jar https://repo1.maven.org/maven2/org/apache/fluss/fluss-fs-s3/0.8.0-incubating/fluss-fs-s3-0.8.0-incubating.jar

